server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1/universe?currentSchema=milkyway
    username: postgres
    password: 123456

site:
  andromeda: http://127.0.0.1:60002/andromeda
  carina: http://127.0.0.1:60006/carina
  leob: http://127.0.0.1:60005/leob
